### ISSUE TITLE
Nifty project!

### ISSUE THREAD

**Issue by billiegoose** [IanSeyler/netLib#1]
There's only 3 commits and none since 2014... is it bad that I chose *this* library to integrate into my next-generation JavaScript platform? 😁 Admittedly, I was a *little* biased towards it because I was already impressed with Pure64 and BareMetal OS...

It seems to work though. And like, it worked on the first try. And (cross my fingers) works cross-platform. And was only one .c file and one .h file. I mean, it's perfect. I'm over the moon! (What's the catch? What am I missing?)

Anyway just wanted to thank you and... wait seriously? How does this only have 3 stars? #confused

And yes, I am trying to run JavaScript on bare metal, eventually. You can witness the craziness over at the [dukboot](https://gitlab.com/wmhilton/dukboot) repo.

**Comment by IanSeyler** [comment]
Thanks! This code hasn't been updated since 2007 but nor has basic networking for that matter. Everything should still work as expected.

netLib is just a wrapper for the OS calls. This allows you to call the netLib functions and netLib will call the OS.

Keep in mind that netLib requires a TCP/IP stack so it wouldn't run on bare metal. However I may add TCP/IP to the BareMetal kernel.

**Comment by billiegoose** [comment]
Yes, I realize it's just a wrapper. But it's a very nice wrapper. And I realize I'm a ways off from running JS on bare metal. I'm not going to be able to avoid system calls and the C standard library for version 1.0. But I'm picking small, single purpose libraries such as netLib over large do-everything libraries like libuv so that in the future refactoring the code to bypass glibc/linux will be more manageable.
